#ifndef _IntersonCxxIntersonClass_h
#define _IntersonCxxIntersonClass_h

// Export library, autogenerated using Cmake
#include "IntersonCxx_Export.h"

#include <string>

// Namespace similar to Interson Namespace from SDK

/*
The library is organized via namespaces; the root is “Interson”,
then “Interson.Controls” to get the methods which access to the 
USB probe controls, “Interson.Imaging” is the scan converter, to 
build the 2D image B-Scan bitmap from the log-compressed A-Scan 
vectors.
*/
namespace IntersonCxx
{
	// Wrapper Class for IntersonClass from SDK
	class IntersonClassImpl;

	// IntersonClass similar to IntersonClass from SDK
	class IntersonCxx_EXPORT IntersonClass
	{
		public:
		  IntersonClass();
		  ~IntersonClass();

		  /*
			Summary: To Get the version of Interson.dll
			Returns: Returns the String of the version.
		  */
		  std::string Version() const;

		private:
		  IntersonClass( const IntersonClass & );
		  void operator=( const IntersonClass & );

		  // Add the wrapper to the main class to use dll function in C#
		  IntersonClassImpl * Impl;
	};

} // end namespace IntersonCxx

#endif // _IntersonCxxIntersonClass_h
